Feature search book
mihhus/intern-line-bot pull request #2
Opened 2019-09-25 06:05 UTC by mihhus

ユーザが書籍の名前もしくは著者名を入力すると該当する書籍のタイトルを10冊表示する機能を追加しました

2019-09-25 07:23 UTC, maruta-giftee approved these changes

2019-09-25 07:23 UTC, maruta-giftee commented on app/controllers/webhook_controller.rb
> +					response = JSON.parse(Net::HTTP.get(URI.parse("https://www.googleapis.com/books/v1/volumes?q=" + URI.escape(event.message['text'], /[^-_.!~*'()a-zA-Z\d]/u))))
[nits] インデントが統一されていませんね。
エディタの設定を直したほうがいいかもしれません。

細かい点ではありますが、こういった部分でコードの品質というのが左右されてしまうので修正をお願いします

2019-09-25 07:23 UTC, maruta-giftee reviewed
間違ってApproveしちゃいました・・・。
コメント範囲の修正をお願いします:pray:

2019-09-25 07:34 UTC, maruta-giftee requested changes

2019-09-25 07:34 UTC, maruta-giftee commented on app/controllers/webhook_controller.rb
> +					response = JSON.parse(Net::HTTP.get(URI.parse("https://www.googleapis.com/books/v1/volumes?q=" + URI.escape(event.message['text'], /[^-_.!~*'()a-zA-Z\d]/u))))
[must] エンドポイント（`https://www.googleapis`）は定数に切り出しましょう。
現状だと変更に弱いです。

2019-09-25 07:34 UTC, maruta-giftee commented on app/controllers/webhook_controller.rb
> +					response = JSON.parse(Net::HTTP.get(URI.parse("http://api.calil.jp/library?appkey=b8c0e0e67846679920a4eae16a42cc07&geocode=#{longitude},#{latitude}&limit=10&format=json&callback= ")))
[must] こちらも同様。定数に切り出しましょう。

[ask] ちなみになのですが、これ、向こうからレスポンスでエラーが返ってきた場合どうなりますか？

2019-09-25 07:36 UTC, maruta-giftee commented on app/controllers/webhook_controller.rb
> +					for index in 0..9 do
[ask] これって、ちゃんと0番目がもっとも一致率の高いものになってるんですかね？（まぁ、そこまで調べるんだっけ？という話ではありますが・・・）

2019-09-25 09:56 UTC, HiroyukiNakatsuma reviewed
@mihhus 1点だけコメントしてみました！

2019-09-25 09:56 UTC, HiroyukiNakatsuma commented on app/controllers/webhook_controller.rb
> +        calil_appkey = ENV["CALIL_APPKEY"]
👍

2019-09-25 09:56 UTC, HiroyukiNakatsuma commented on app/controllers/webhook_controller.rb
> +          end
@mihhus [nits] (最終的にここの実装が残るかわからないですが、参考情報としてお伝えすると) こんな風にも書けます。(こっちの方が ruby っぽい書き方かも)
```
response['items'].each do |item|
    text += item['volumeInfo']['title'] + "\n"
end
```

あと、 `+=` より `<<` で連結させた方が速い説もあるそうです(公式docではないのでなんとも言えないですが)
https://qiita.com/Kta-M/items/c7c2fb0b61b11d3a2c48

2019-09-26 03:15 UTC, maruta-giftee commented on app/controllers/webhook_controller.rb
> +          endpoint = "https://www.googleapis.com"
[nits][imo] これprivateな定数にしてしまったほうがいいですね。
when内部に書くと毎回文字列生成してしまうのでコストがかかります（処理速度的には誤差ですが元アルゴリズムマンとしては看過できなかった・・・）

2019-09-26 03:15 UTC, maruta-giftee commented on app/controllers/webhook_controller.rb
> +          response = JSON.parse(Net::HTTP.get(URI.parse(endpoint + "/books/v1/volumes?q=" + user_query)))
[ask] これ、Net::HTTP.getのレスポンスがエラーだったらどうなるでしょうか？
parseできなくて500エラーが出ちゃう気がしています

[imo]ですが、例えば

```
# get_books_url関数は本情報取得APIのURLを返すと仮定
uri = URI.parse(get_books_url)
response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
        http.open_timeout = 1
        http.read_timeout = 10
        http.get(uri.request_uri)
      end
```

のようにして、レスポンスについて

```
case response
when Net::HTTPSuccess
  Rails.logger.info("やったぜ")
when ほげほげ
```

みたいに条件分岐したほうが安全ですね

FYI: https://docs.ruby-lang.org/ja/latest/library/net=2fhttp.html

2019-09-26 06:46 UTC, mihhus commented on app/controllers/webhook_controller.rb
> +          response = JSON.parse(Net::HTTP.get(URI.parse(endpoint + "/books/v1/volumes?q=" + user_query)))
Net::HTTP.startで接続に失敗した際例外が発生するっぽいので, 例外処理で書いてみることにします

2019-09-26 08:41 UTC, maruta-giftee approved these changes

2019-09-26 09:33 UTC, HiroyukiNakatsuma approved these changes
@mihhus LGTM!!!

2019-09-26 09:34 UTC, merged